#!/bin/bash

# Start Financial Analysis Execution Engine
# This script starts the execution engine that executes tool call plans

echo "Starting Financial Analysis Execution Engine..."
echo "Execution engine will be available at: http://localhost:8003"
echo "API Documentation at: http://localhost:8003/docs"
echo ""
echo "This execution engine will:"
echo "- Execute tool call plans generated by ollama-server" 
echo "- Orchestrate calls to multiple MCP servers"
echo "- Return structured JSON results for QnA frontend"
echo "- Handle errors gracefully with partial results"
echo ""
echo "Make sure you have:"
echo "1. MCP HTTP wrappers running: ./start-mcp-wrappers.sh"
echo "2. Financial server wrapper: http://localhost:8001"
echo "3. Analytics server wrapper: http://localhost:8002"
echo ""
echo "Press Ctrl+C to stop the execution engine."
echo ""

cd "$(dirname "$0")"
python execution-engine.py